### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Digitalroot** [Rabadash8820/UnityAssemblies#11]
I just want to say thank you!

**Comment by Rabadash8820** [comment]
@Digitalroot You are so welcome! This is one of my first forays into open-source, so its great to hear some positive feedback. 😃  I'd love to know how you're using this library in your projects, or if you have any suggestions for future improvement.

**Comment by Digitalroot** [comment]
Valheim modding. https://github.com/Digitalroot-Valheim

Your readme was 100% my use case. There are no good nuget packages for getting the UnityEditor dll. BepInEx has a good nuget package for the Engine dll, but not the editor or other modules.

**Comment by Rabadash8820** [comment]
Oh awesome! I didn't get much into the modding scene when I played _Valheim_; guess I'll have to give it another try. 😎 Didn't even realize that game was made with Unity! On a side note, I saw that you're also the maintainer of projecteuler.net. I love that site! I have it bookmarked for when I'm bored lol, and I often point people who are new to programming at it for some practice.

So glad the README helped you out. `UnityEditor` and `UnityEngine.UI` are what sold me on the idea for a new package as well. Most packages just say "here's UnityEngine.dll" and never update it, or even tell you which version they've included in the package... Anyway, tell your friends lol, I'd love to see people stop recommending those out-dated packages on the forums. 

Since there's obviously no work to do here I'm gonna close this Issue, but thanks again for the support and sharing your use case!
