### ISSUE TITLE
Allow defining Unity install path by an environment variable

### ISSUE THREAD

**Issue by laicasaane** [Rabadash8820/UnityAssemblies#13]
I think it's unreasonable to only allow defining Unity install path by `UnityInstallRootPath`, it will be hard-coded into the project, since the programs directory can be different from person to person. I suggest we should check an environment variable (`UNITY_INSTALL_PATH`) at first, and only if it does not exist or somehow incorrect, we would fall back to `UnityInstallRootPath`.

**Comment by Rabadash8820** [comment]
@laicasaane Thanks for raising this issue. To clarify, `UnityInstallRootPath` is basically determined by Unity; while I provided the ability to change this property, I can't imagine a reason _to_ change it with the existing versions of Unity, so I assume you're actually talking about `OSInstallRootPath`. MSBuild already provides several solutions for users to override this property:

1. Use MSBuild [property functions](https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022) in your version-controlled `OSInstallRootPath`. You could require all team members to agree on a particular install location. For example, if everyone was using Windows and required to install Unity at `D:\Unity`, then you could set the following property in your `.props` file:

    ```xml
    <OSInstallRootPath>D:\Unity</OSInstallRootPath>
   ```

    To require everyone to install Unity at a `Unity` subfolder of their home directory, you would set:
        
    ```xml
    <OSInstallRootPath>$([System.Environment]::GetFolderPath('System.Environment+SpecialFolder.UserProfile'))</OSInstallRootPath>
    ```

    Alternatively, as you suggested, you could read from an environment variable to give each contributor the option to use an entirely custom install location. Each collaborator would need to define that variable on their machine. Set:

    ```xml
    <OSInstallRootPath>$([System.Environment]::GetEnvironmentVariable('UNITY_INSTALL_PATH'))</OSInstallRootPath>
    ```

2. Use a [.user file](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#user-file). This would allow everyone to set their own install location by adding a `<YourProject>.csproj.user` file adjacent to the `<YourProject>.csproj` file, and hard-coding `OSInstallRootPath` in that file. You would want to add a `.gitignore` rule or similar file for your version control system to make sure users don't accidentally commit that file.

Of the above, I personally think 2) is more flexible, as it allows users to override _any_ property in a more MSBuild-native way, rather than adding a bunch of property-specific environment variables. However, the `GetEnvironmentVariable` approach in 1) should address your immediate use case. I'll keep this Issue open for a little bit while you try these solutions, in case they don't work as intended.

**Comment by Rabadash8820** [comment]
Also, FWIW, I realize that the Readme instructions on this were a little outdated/misleading. That's probably why you were talking about `UnityInstallRootPath`. I have [updated that section](https://github.com/Rabadash8820/UnityAssemblies#referencing-assemblies-at-non-default-install-locations) accordingly.

**Comment by laicasaane** [comment]
Thanks for your help! However, for me `OSInstallRootPath` is not enough. I have to override `UnityInstallRootPath`.

For the `.user` file, it doesn't seem to work for me too, or I might set it up the wrong way? I've renamed it to either `MyProject.csproj.user` or `MyProject.user`, and the content is:

```
<Project>
    <PropertyGroup>
        <UnityInstallRootPath>C:/Programs/Unity</UnityInstallRootPath>
    </PropertyGroup>
</Project>
```

**Comment by Rabadash8820** [comment]
Ah, yes I gave you some misinformation. The `.user` file doc that I linked mentions that these files are accessible to MSBuild projects using `Microsoft.Common.CurrentVersion.targets`. However, the .NET Standard 2.x projects required for working with Unity APIs do _not_ use that target apparently. Just confirmed this in a test solution (probably should've done that before suggesting it. 🙄). So I guess you _will_ have to use `GetEnvironmentVariable` or another MSBuild property function to support user-specific Unity install locations.

**Comment by laicasaane** [comment]
It's ok. This is just a demo about using UnityAssemblies after all. I think it would be fine to depend on environment variables as long as my documentation is clear about it, until Unity done upgrading their CoreCLR and build process.

**Comment by Rabadash8820** [comment]
Makes sense. And yes, hopefully official CoreCLR support comes soon 😬 Out of curiosity, where will the demo be posted? I'm honored that you want to share this project with others!

**Comment by laicasaane** [comment]
It is just a local demo, mainly out of curiosity. Actually, I did intend to use this in a [tutorial](https://github.com/laicasaane/unity.source-generator.demo) about how to set up a source generator UPM package step by step. However for now I have no actual use for UnityAssemblies so I didn't commit it to the remote repo.
