### ISSUE TITLE
UnityEditor DLLs not referenced

### ISSUE THREAD

**Issue by miyu** [Rabadash8820/UnityAssemblies#19]
FYI, I'm locally including UnityEditor DLLs as follows. It'd be great if depending on editor DLLs were supported always or via a flag.

```csharp
    <ItemGroup Condition="'$(IncludeDefaultUnityAssemblyReferences)'=='True'">
        <!-- Don't use the usual monolithic UnityEngine.dll by default, as it conflicts with the module references required for many UPM package assemblies. -->
        <!-- Don't use `UnityEngine*.dll` as the pattern either. That feels too general and might match assemblies in the future that we DON'T want by default. -->
        <Reference Include="$(UnityModulesPath)\UnityEngine.dll" Private="false" />
        <Reference Include="$(UnityModulesPath)\UnityEngine.*Module.dll" Private="false" />
        <Reference Include="$(UnityModulesPath)\UnityEditor.dll" Private="false" />
        <Reference Include="$(UnityModulesPath)\UnityEditor.*Module.dll" Private="false" />
    </ItemGroup>
```

For example, this lets me hit `EditorApplication` from my code.

**Comment by Rabadash8820** [comment]
@miyu Not sure I follow. I don't think Editor DLLs should "always" be referenced, as those references will never work in built Unity players. I think that adding those references manually is a good way to be sure that one really wants an Editor-only managed plugin. As for a flag, can you put another code snippet showing how your previous example would change?

**Comment by starikcetin** [comment]
@Rabadash8820 How about this:
```xml
<PropertyGroup>
  <ReferenceUnityEditor>true</ReferenceUnityEditor>
</PropertyGroup>
```
You can make it `false` by default.

**Comment by miyu** [comment]
Yeah and the reference would be conditional, sorta like the `Condition="'$(IncludeDefaultUnityAssemblyReferences)'=='True'">` part of my snippet above

**Comment by Rabadash8820** [comment]
I see. So first of all, @miyu, your example project file could already be reduced to the following, since `$(IncludeDefaultUnityAssemblyReferences)` (which includes all the UnityEngine module DLLs) is `True` by default, and the assembly at `$(UnityEditorPath)` (`C:\Program Files\Unity\Hub\Editor\$(UnityVersion)\Editor\Data\Managed\UnityEditor.dll` by default on Windows) includes all UnityEditor modules (at least to my knowledge).

```xml
<ItemGroup>
    <Reference Include="$(UnityEditorPath)" Private="false" />
</ItemGroup>
```

With that single `Reference`, I see no need for a new flag. @miyu  can you confirm whether the above is sufficient for referencing the UnityEditor types that you need?

**Comment by Rabadash8820** [comment]
@miyu Hopefully my suggestion helped you. I'm closing this Issue now, but feel free to re-open if not.
